-- SQUADS
INSERT INTO TB_SQUAD (DS_NAME) VALUES  ('MS SUBSCRIPTIONS');
INSERT INTO TB_SQUAD (DS_NAME) VALUES  ('MS ORDERS');
INSERT INTO TB_SQUAD (DS_NAME) VALUES  ('MS CUSTOMERS');
INSERT INTO TB_SQUAD (DS_NAME) VALUES  ('MS STOCKS');

-- MEMBERS

INSERT INTO TB_MEMBER (ID_SQUAD, DS_NAME, DS_JOB_TITLE) VALUES (1,'MARCOS','DEV JAVA');
INSERT INTO TB_MEMBER (ID_SQUAD, DS_NAME, DS_JOB_TITLE) VALUES (2,'NILVAN','GESTOR');