CREATE TABLE TB_SQUAD 
(
    ID_SQUAD INTEGER NOT NULL AUTO_INCREMENT,
    DS_NAME VARCHAR(50),
    PRIMARY KEY (ID_SQUAD)
);

CREATE TABLE TB_MEMBER
(
    ID_MEMBER INTEGER NOT NULL AUTO_INCREMENT,
    ID_SQUAD INTEGER NOT NULL,
    DS_NAME VARCHAR(50),
    DS_JOB_TITLE VARCHAR(50),
    PRIMARY KEY( ID_MEMBER),
    FOREIGN KEY (ID_SQUAD) REFERENCES TB_SQUAD(ID_SQUAD)
);
